notifications:
  slack: livoniawarriors:WlPFlm1wbRWJ6GlWtEQLFWfG
sudo: false
language: java
install: true
before_install:
- chmod +x gradlew
- mkdir lib/
- wget --no-check-certificate 'https://docs.google.com/uc?export=download&id=1w6vrVvmJthSR0ZLOVddlKqDQ49GPCqlE' -P "lib/"  -O 'SparkMax-java-1.0.26.jar'
script: ./gradlew build
jdk: oraclejdk11
